version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0"]
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  api:
    build:
      context: ./src
      dockerfile: API/Dockerfile
    container_name: api
    ports:
      - "5040:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - mongo
      - redis
      - minio

volumes:
  mongo-data:
  minio-data: